from hashlib import sha1
import os
import shutil

from .enums import RaceMode, Tracks
from .HotWheels import HotWheelsEnv
from .RAMOpponent import (
    DinoRAMModelOpponentEnv,
    DinoRAMPlayerEnv,
    RAMActionRepeat,
)

GAME_NAME = "HotWheelsStuntTrackChallenge-GbAdvance"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

__all__ = [
    "import_rom",
    "make",
    "HotWheelsEnv",
    "DinoRAMPlayerEnv",
    "DinoRAMModelOpponentEnv",
    "RAMActionRepeat",
    "GAME_NAME",
]


def import_rom(path_to_rom, *, force: bool = False) -> None:
    """
    Copy the ROM file into the custom game integration folder
    """
    abs_rom_path = os.path.abspath(path_to_rom)
    if not abs_rom_path.lower().endswith(".gba"):
        raise ValueError("ROM import path must end with .gba")
    if not os.path.isfile(abs_rom_path):
        raise FileNotFoundError(abs_rom_path)

    custom_integration_path = os.path.join(SCRIPT_DIR, GAME_NAME, "rom.gba")
    with open(abs_rom_path, "rb") as handle:
        digest = sha1(handle.read()).hexdigest()
    with open(os.path.join(SCRIPT_DIR, GAME_NAME, "rom.sha")) as handle:
        supported_hashes = set(handle.read().split())
    if digest not in supported_hashes:
        raise ValueError(
            f"unsupported ROM SHA-1 {digest}; expected the original ROM or a "
            "ROM generated by the bundled NPC patch tool"
        )

    if os.path.isfile(custom_integration_path) and not force:
        return
    print(f"Copying {abs_rom_path} to {custom_integration_path}")
    shutil.copy(abs_rom_path, custom_integration_path)


def make(id: str, **kwargs) -> HotWheelsEnv:
    """Make a HotWheelsEnv from an ID"""
    try:
        _, track, mode, laps = id.split("-")
    except ValueError:
        print(
            f"Got ID with invalid format {id}. The correct format is HWSTC-<track>-<mode>-<laps>"
        )
        raise

    if Tracks(track) not in Tracks:
        print(f"ERROR! Got invalid track {track}")
        return

    if RaceMode(mode) not in RaceMode:
        print(f"ERROR! Got invalid mode {mode}")
        return

    if int(laps) not in {1, 2, 3}:
        print(f"ERROR! Got invalid lap {laps}")
        return

    return HotWheelsEnv(
        track=Tracks(track),
        mode=RaceMode(mode),
        total_laps=int(laps),
        **kwargs,
    )
